# $HOME/.config/alacritty/alacritty.toml
# import = ["~/.config/alacritty/themes/themes/pepe.toml"]

[shell]
program = "/bin/zsh"

[window]
# opacity = 0.85
decorations_theme_variant = "Dark"
padding.x = 0
padding.y = 0
decorations = "Full"

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"
size = 16.5

[mouse]
hide_when_typing = true
