# $HOME/.config/alacritty/alacritty.toml
import = ["~/.config/alacritty/themes/themes/pepe.toml"]

[shell]
program = "/bin/zsh"

[window]
opacity = 0.85
decorations_theme_variant = "Dark"
padding.x = 0
padding.y = 0
decorations = "Full"

[font]
normal.family = "Hack Nerd Font"
bold.family = "JetBrains Mono NL"
italic.family = "RobotoMono Nerd Font"
bold_italic.family = "RobotoMono Nerd Font"
size = 16.5

[mouse]
hide_when_typing = true
